import { MdSentimentVerySatisfied } from "react-icons/md";
import { GiBabyBottle, GiBabyFace } from "react-icons/gi";
import { FaBabyCarriage } from "react-icons/fa";

// export const homeData = [
//   {
//     id: 1,
//     name: "Nataniel",
//     rating: <MdSentimentVerySatisfied />,
//     time: "9 : 18",
//     desc: "Nataniel to imię pochodzenia hebrajskiego. Tłumaczyć je można jako 'dany od Boga' lub 'podarowany przez Boga'. Obecnie imię Nataniel nosi 867 Polaków.",
//     starring: " Natanielek, Natanielcio, Talutek, Tanieluś.",
//     genres: " 24 sierpnia.",
//     tags: " Nat King Cole (właśc. Nathaniel Adams Coles, 1919-1965) - amerykański pianista i wokalista jazzowy.",
//     cover: "../images/2.jpg",
//     video: "../video/1.mp4",
//     date: "13.06.2022",
//     nameL: " Nathanael, Nathaniel.",
//     lang: " po angielsku",
//     desc1: "imieniny: 24 lipca, 25 grudnia",
//     desc2:
//       "Zapis Nataniel to zapis hiszpański i portugalski tego imienia, w tym samym wariancie spotyka się go również w Polsce.",
//     desc3:
//       "To imię również nosi planetoida odkryta w 1998 r. Pochodzi ona z pasa głównego asteroid, okrążająca Słońce w ciągu 5,3 lat.",
//   },
//   {
//     id: 2,
//     name: "Nataniel",
//     rating: <MdSentimentVerySatisfied />,
//     time: "9 : 41",
//     desc: "Znaczeniowo przypomina takie imiona, jak greckie z pochodzenia Teodor czy polskie Bożydar.",
//     starring: " Natanieluś, Natanek, Natan, Natuniek, Naćko, Nejt, Tan.",
//     genres: "Action",
//     tags: " Nathaniel Baldwin – amerykański naukowiec i wynalazca.",
//     cover: "../images/5.jpg",
//     video: "../video/2.mp4",
//     date: "13.06.2022",
//     nameL: " Nathaniel.",
//     lang: " po niemiecku",
//     desc1: "W polszczyźnie przyjęły się dwa imiona biblijne: Natan i Natanael.",
//     desc2: "Imię Natan występuje także w Starym Testamencie.",
//     desc3:
//       "Jezus ujrzał jak Natanael zbliżał się do Niego i mówi o nim: „Patrz, to prawdziwy Izraelita – bez podstępu”.",
//   },
//   {
//     id: 3,
//     name: "Nataniel",
//     rating: <MdSentimentVerySatisfied />,
//     time: "15 : 38",
//     desc: "Imieniem Natanael nazywany był w Piśmie Świętym – apostoł Bartłomiej, który na świat przyszedł w pierwszym wieku naszej ery.",
//     starring: " Natanuś, Nati, Nelek, Tanek.",
//     genres: "Adventures",
//     tags: " Nathaniel Hawthorne – pisarz romantyczny, uważany za jednego z największych i najbardziej wpływowych twórców literatury amerykańskiej XIX wieku.",
//     cover: "../images/4.jpg",
//     video: "../video/9.mp4",
//     date: "13.06.2022",
//     nameL: " Natanaele.",
//     lang: " po włosku",
//     desc1:
//       "Kult św. Bartłomieja datowany jest od V wieku, kościół łaciński święto Apostoła, od wieku VIII obchodzi 24 sierpnia.",
//     desc2:
//       "W ikonografii św. Bartłomiej przedstawiany jest w długiej tunice, przepasanej paskiem.",
//     desc3:
//       "Grecy obchodzą jego uroczystość 11 czerwca, Ormianie 8 grudnia i 25 lutego, Etiopczycy 18 lipca i 20 listopada.",
//   },
//   {
//     id: 4,
//     name: "Nataniel",
//     rating: <MdSentimentVerySatisfied />,
//     time: "12 : 42",
//     desc: "Znak zodiaku - Bliźnięta.",
//     starring: " Natko, Nateczek, Natkuś, Taniel, Tanielek.",
//     genres: "Adventures",
//     tags: " Nathaniel Parker – brytyjski aktor teatralny, filmowy i telewizyjny.",
//     cover: "../images/3.jpg",
//     video: "../video/4.mp4",
//     date: "15.06.2022",
//     nameL: " Nathanaël.",
//     lang: " po łacinie",
//     desc1: "Imię Natanael jest dwukrotnie odnotowane w Ewangelii św. Jana.",
//     desc2:
//       "W Nowym Testamencie mię to nosił jeden z uczniów Jezusa, często utożsamiany z Bartłomiejem Apostołem.",
//     desc3:
//       "Pojawia się on pod koniec Ewangelii według świętego Jana, jak i w Dziejach Apostolskich.",
//   },
// ];

// export const upcome = [
//   {
//     id: 1,
//     cover: "../images/upcome/3.jpg",
//     name: "13.06.2022",
//     time: "09 : 13",
//     link: "//www.pampers.pl/noworodek",
//   },
//   {
//     id: 2,
//     cover: "../images/upcome/1.jpg",
//     name: "14.06.2022",
//     time: "10 : 36",
//   },
//   {
//     id: 3,
//     cover: "../images/upcome/5.jpg",
//     name: "14.06.2022",
//     time: "10 : 36",
//   },
//   {
//     id: 4,
//     cover: "../images/upcome/52.jpg",
//     name: "14.06.2022",
//     time: "09 : 13",
//     link: "//www.pampers.pl/noworodek",
//   },
//   {
//     id: 5,
//     cover: "../images/upcome/2.jpg",
//     name: "14.06.2022",
//     time: "10 : 37",
//   },
//   {
//     id: 6,
//     cover: "../images/upcome/4.jpg",
//     name: "20.06.2022",
//     time: "09 : 36",
//   },
// ];

// export const latest = [
//   {
//     id: 1,
//     cover: "../images/upcome/6.jpg",
//     name: "13.06.2022",
//     time: "09 : 13",
//   },
//   {
//     id: 2,
//     cover: "../images/upcome/7.jpg",
//     name: "14.06.2022",
//     time: "10 : 36",
//   },
//   {
//     id: 3,
//     cover: "../images/upcome/8.jpg",
//     name: "16.06.2022",
//     time: "14 : 48",
//   },
//   {
//     id: 4,
//     cover: "../images/upcome/9.jpg",
//     name: "17.06.2022",
//     time: "11 : 19",
//   },
//   {
//     id: 5,
//     cover: "../images/upcome/10.jpg",
//     name: "23.06.2022",
//     time: "10 : 08",
//   },
// ];

// export const trending = [
//   {
//     id: 1,
//     name: "Natanek",
//     rating: <GiBabyBottle />,
//     time: "09 : 28",
//     desc: "Śpi ponad 16 godzin na dobę.",
//     starring: "Natek, Nat, Natuś",
//     genres: "Action",
//     tags: "Nathaniel C. Wyeth – amerykański wynalazca, twórca tworzywa PET.",
//     cover: "../images/img/1.jpg",
//     date: "22.06.2022",
//     nameL: " Nathanael.",
//     lang: " po grecku",
//   },
//   {
//     id: 2,
//     name: "Natanuś",
//     rating: <FaBabyCarriage />,
//     time: "09 : 28",
//     desc: "Bardzo lubi się kąpać. W wodzie uśmiecha się.",
//     starring: "Natusiek, Natuniek, Nejtan",
//     genres: "Adventures",
//     tags: "Nathaniel Rateliff – amerykański piosenkarz.",
//     cover: "../images/img/2.jpg",
//     date: "22.06.2022",
//     nameL: " Nathanaël.",
//     lang: " po francusku",
//   },
//   {
//     id: 3,
//     name: "Nateczek",
//     rating: <GiBabyFace />,
//     time: "09 : 36",
//     desc: "Umie ssać pierś przez nakładkę. Mleczko mamy bardzo mu smakuje.",
//     starring: "Nielek, Tal, Talek",
//     genres: "Adventures",
//     tags: "Nathaniel Clyne – angielski piłkarz.",
//     cover: "../images/img/3.jpg",
//     date: "20.06.2022",
//     nameL: " Natanael.",
//     lang: " po czesku",
//   },
// ];
export const recommended = [
  {
    id: 1,
    cover: "../images/1.jpg",
    name: "Już jestem w ubranku",
    time: "15 : 14",
    date: "23.06.2022",
  },
  {
    id: 2,
    cover: "../images/upcome/14.jpg",
    name: "Razem z tatą",
    time: "10 : 51",
  },
  {
    id: 3,
    cover: "../images/upcome/16.jpg",
    name: "Ja i tata",
    time: "10 : 51",
  },

  // {
  //   id: 4,
  //   cover: "../images/upcome/17.jpg",
  //   name: "Duma taty",
  //   time: "10 : 51",
  // },
  // {
  //   id: 5,
  //   cover: "../images/upcome/13.jpg",
  //   name: "Kolorowy sen",
  //   time: "10 : 51",
  // },
  // {
  //   id: 6,
  //   cover: "../images/upcome/15.jpg",
  //   name: "W całej okazałości",
  //   time: "10 : 51",
  // },
  // {
  //   id: 7,
  //   cover: "../images/upcome/18.jpg",
  //   name: "Kto mnie budzi?",
  //   time: "10 : 51",
  // },
  // {
  //   id: 8,
  //   cover: "../images/rec/1.jpg",
  //   name: "W wytwornej czapeczce",
  //   time: "10 : 51",
  // },
  // {
  //   id: 9,
  //   cover: "../images/rec/3.jpg",
  //   name: "W wózku z maskotką",
  //   time: "15 : 35",
  // },
  // {
  //   id: 10,
  //   cover: "../images/rec/2.jpg",
  //   name: "Myślę, więc jestem",
  //   time: "10 : 08",
  // },
  // {
  //   id: 11,
  //   cover: "../images/rec/11.jpg",
  //   name: "W fotelu z mamą",
  //   time: "14 : 06",
  // },
  // {
  //   id: 12,
  //   cover: "../images/upcome/11.jpg",
  //   name: "Idzie lato",
  //   time: "20 : 44",
  // },
  // {
  //   id: 13,
  //   cover: "../images/upcome/12.jpg",
  //   name: "Nie przegrzewam się",
  //   time: "20 : 47",
  // },
  // {
  //   id: 14,
  //   cover: "../images/upcome/19.jpg",
  //   name: "Świat jest ciekawy",
  //   time: "19 : 38",
  // },
  // {
  //   id: 15,
  //   cover: "../images/upcome/20.jpg",
  //   name: "Jestem tutaj",
  //   time: "19 : 38",
  // },
  // {
  //   id: 16,
  //   cover: "../images/upcome/21.jpg",
  //   name: "W body",
  //   time: "19 : 06",
  // },
  // {
  //   id: 17,
  //   cover: "../images/upcome/22.jpg",
  //   name: "W łóżeczku",
  //   time: "20 : 26",
  // },
  // {
  //   id: 18,
  //   cover: "../images/upcome/23.jpg",
  //   name: "Blisko mamy i taty",
  //   time: "20 : 26",
  // },
  // {
  //   id: 19,
  //   cover: "../images/upcome/24.jpg",
  //   name: "Z elektronicznym misiem",
  //   time: "17 : 56",
  // },
  // {
  //   id: 20,
  //   cover: "../images/upcome/25.jpg",
  //   name: "Miś czuwa, gdy ja śpię",
  //   time: "14 : 44",
  // },
  // {
  //   id: 21,
  //   cover: "../images/upcome/28.jpg",
  //   name: "Trochę na boczku",
  //   time: "17 : 07",
  // },
  // {
  //   id: 22,
  //   cover: "../images/upcome/54.jpg",
  //   name: "Trochę u mamy",
  //   time: "17 : 07",
  // },
  // {
  //   id: 23,
  //   cover: "../images/upcome/26.jpg",
  //   name: "Rozglądam się po pokoju",
  //   time: "15 : 07",
  // },
  // {
  //   id: 24,
  //   cover: "../images/upcome/27.jpg",
  //   name: "Nie zawsze tylko śpię",
  //   time: "15 : 07",
  // },
  // {
  //   id: 25,
  //   cover: "../images/upcome/29.jpg",
  //   name: "Na pajacyka",
  //   time: "10 : 23",
  // },
  // {
  //   id: 26,
  //   cover: "../images/upcome/30.jpg",
  //   name: "Znowu zmorzył mnie sen",
  //   time: "10 : 21",
  // },
  // {
  //   id: 27,
  //   cover: "../images/upcome/31.jpg",
  //   name: "Teraz na drugim boczku",
  //   time: "19 : 37",
  // },
  // {
  //   id: 28,
  //   cover: "../images/upcome/32.jpg",
  //   name: "Bez smoczka nie dam rady",
  //   time: "19 : 08",
  // },
  // {
  //   id: 29,
  //   cover: "../images/upcome/36.jpg",
  //   name: "Nie ma to jak dobrze się wyspać",
  //   time: "20 : 38",
  // },
  // {
  //   id: 30,
  //   cover: "../images/upcome/37.jpg",
  //   name: "Mam już 1-szy miesiąc",
  //   time: "13 : 09",
  // },
  // {
  //   id: 31,
  //   cover: "../images/upcome/38.jpg",
  //   name: "Zafundowałem sobie nową fryzurę",
  //   time: "13 : 09",
  // },
  // {
  //   id: 32,
  //   cover: "../images/upcome/39.jpg",
  //   name: "Na klacie u taty",
  //   time: "13 : 09",
  // },
  // {
  //   id: 33,
  //   cover: "../images/upcome/40.jpg",
  //   name: "Lubię smonia",
  //   time: "13 : 09",
  // },
  // {
  //   id: 34,
  //   cover: "../images/upcome/41.jpg",
  //   name: "W podróży autem",
  //   time: "13 : 37",
  // },
  // {
  //   id: 35,
  //   cover: "../images/upcome/42.jpg",
  //   name: "Tak sobie myślę ...",
  //   time: "09 : 53",
  // },
  // {
  //   id: 36,
  //   cover: "../images/upcome/53.jpg",
  //   name: "Właściwie mam jeszcze czas na myślenie",
  //   time: "09 : 53",
  // },
  // {
  //   id: 37,
  //   cover: "../images/upcome/43.jpg",
  //   name: "Z misiem jest mi dobrze",
  //   time: "09 : 53",
  // },
  // {
  //   id: 38,
  //   cover: "../images/upcome/44.jpg",
  //   name: "Razem raźniej",
  //   time: "09 : 53",
  // },
  // {
  //   id: 39,
  //   cover: "../images/upcome/45.jpg",
  //   name: "Błogi sen",
  //   time: "12 : 02",
  // },
  // {
  //   id: 40,
  //   cover: "../images/upcome/46.jpg",
  //   name: "Lubię sobie pospać",
  //   time: "12 : 02",
  // },
  // {
  //   id: 41,
  //   cover: "../images/upcome/50.jpg",
  //   name: "Coś mi lata nad głową",
  //   time: "13 : 43",
  // },
  // {
  //   id: 42,
  //   cover: "../images/upcome/51.jpg",
  //   name: "Może jednak bym coś poczytał",
  //   time: "13 : 43",
  // },
  // {
  //   id: 43,
  //   cover: "../images/upcome/54.jpg",
  //   name: "Najwygodniej w body",
  //   time: "17 : 24",
  // },
  // {
  //   id: 44,
  //   cover: "../images/upcome/56.jpg",
  //   name: "Mama nie żałuje mleczka",
  //   time: "08 : 50",
  // },
  // {
  //   id: 45,
  //   cover: "../images/upcome/55.jpg",
  //   name: "Wszystko bym oddał za mleczko",
  //   time: "08 : 53",
  // },
  // {
  //   id: 46,
  //   cover: "../images/upcome/57.jpg",
  //   name: "Pępuszek - kwiatuszek",
  //   time: "13 : 31",
  // },
  // {
  //   id: 47,
  //   cover: "../images/upcome/59.jpg",
  //   name: "Jestem bardzo zadowolony",
  //   time: "12 : 21",
  // },
  // {
  //   id: 48,
  //   cover: "../images/upcome/58.jpg",
  //   name: "Cała przyjemność po mojej stronie",
  //   time: "12 : 22",
  // },
  // {
  //   id: 49,
  //   cover: "../images/upcome/60.jpg",
  //   name: "Mój pierwszy dyplom",
  //   time: "14 : 21",
  // },
  // {
  //   id: 50,
  //   cover: "../images/upcome/61.jpg",
  //   name: "Nie wiem, czy lubię tego misia",
  //   time: "09 : 35",
  // },
  // {
  //   id: 51,
  //   cover: "../images/upcome/62.jpg",
  //   name: "W końcu mamy sierpień",
  //   time: "09 : 35",
  // },
  // {
  //   id: 52,
  //   cover: "../images/upcome/63.jpg",
  //   name: "Prawdziwy śmieszek ze mnie",
  //   time: "11 : 11",
  // },
  // {
  //   id: 53,
  //   cover: "../images/upcome/64.jpg",
  //   name: "Przed domem, na tarasie",
  //   time: "10 : 28",
  // },
  // {
  //   id: 54,
  //   cover: "../images/upcome/65.jpg",
  //   name: "Sen mnie zmorzył",
  //   time: "15 : 12",
  // },
  // {
  //   id: 55,
  //   cover: "../images/upcome/66.jpg",
  //   name: "Z rączkami pod poduszką",
  //   time: "20 : 23",
  // },
  // {
  //   id: 56,
  //   cover: "../images/upcome/67.jpg",
  //   name: "Słucham z zainteresowaniem",
  //   time: "10 : 29",
  // },
  // {
  //   id: 57,
  //   cover: "../images/upcome/68.jpg",
  //   name: "Prezent od Gabrysi i jej rodziców",
  //   time: "10 : 20",
  // },
  // {
  //   id: 58,
  //   cover: "../images/upcome/69.jpg",
  //   name: "Ktoś właśnie opowiedział dowcip",
  //   time: "10 : 28",
  // },
  // {
  //   id: 59,
  //   cover: "../images/upcome/74.jpg",
  //   name: "Ale nie wiem, czy się śmiać",
  //   time: "10 : 28",
  // },
  // {
  //   id: 60,
  //   cover: "../images/upcome/70.jpg",
  //   name: "Może troszeczkę się zaśmieję",
  //   time: "14 : 16",
  // },
  // {
  //   id: 61,
  //   cover: "../images/upcome/71.jpg",
  //   name: "Przyśnił mi się Kubuś Puchatek",
  //   time: "14 : 16",
  // },
  // {
  //   id: 62,
  //   cover: "../images/upcome/72.jpg",
  //   name: "Sierpniowa drzemka po południu",
  //   time: "14 : 16",
  // },
  // {
  //   id: 63,
  //   cover: "../images/upcome/73.jpg",
  //   name: "Boks to mój żywioł",
  //   time: "14 : 16",
  // },
  // {
  //   id: 64,
  //   cover: "../images/upcome/82.jpg",
  //   name: "Robię za tło dla lodów",
  //   time: "09 : 56",
  // },
  // {
  //   id: 65,
  //   cover: "../images/upcome/81.jpg",
  //   name: "W foteliku",
  //   time: "09 : 56",
  // },
  // {
  //   id: 66,
  //   cover: "../images/upcome/80.jpg",
  //   name: "Obok mamy",
  //   time: "09 : 46",
  // },
  // {
  //   id: 67,
  //   cover: "../images/upcome/75.jpg",
  //   name: "Efekty specjalne",
  //   time: "09 : 46",
  // },
  // {
  //   id: 68,
  //   cover: "../images/upcome/76.jpg",
  //   name: "Pod karuzelą",
  //   time: "09 : 46",
  // },
  // {
  //   id: 69,
  //   cover: "../images/upcome/77.jpg",
  //   name: "Złapałem misia za uszko",
  //   time: "09 : 46",
  // },
  // {
  //   id: 70,
  //   cover: "../images/upcome/78.jpg",
  //   name: "Muszę go trochę wytarmosić",
  //   time: "09 : 46",
  // },
  // {
  //   id: 71,
  //   cover: "../images/upcome/79.jpg",
  //   name: "Miś zyskuje przewagę",
  //   time: "09 : 46",
  // },
  // {
  //   id: 72,
  //   cover: "../images/upcome/83.jpg",
  //   name: "Zmęczony walką z misiem zasypiam",
  //   time: "10 : 52",
  // },
  // {
  //   id: 73,
  //   cover: "../images/upcome/84.jpg",
  //   name: "Przesiadłem się z gondoli na spacerówkę",
  //   time: "12 : 30",
  // },
  // {
  //   id: 74,
  //   cover: "../images/upcome/85.jpg",
  //   name: "Ze spacerówki więcej widać",
  //   time: "12 : 30",
  // },
  // {
  //   id: 75,
  //   cover: "../images/upcome/86.jpg",
  //   name: "I nie muszę już tylko leżeć",
  //   time: "12 : 30",
  // },
  // {
  //   id: 76,
  //   cover: "../images/upcome/87.jpg",
  //   name: "Jest mi o wiele wygodniej",
  //   time: "12 : 30",
  // },
  // {
  //   id: 78,
  //   cover: "../images/upcome/88.jpg",
  //   name: "Kto powiedział, że nie umiem się czołgać?",
  //   time: "15 : 44",
  // },
  // {
  //   id: 79,
  //   cover: "../images/upcome/89.jpg",
  //   name: "Ta perspektywa przypadła mi do gustu",
  //   time: "15 : 54",
  // },
  // {
  //   id: 80,
  //   cover: "../images/upcome/90.jpg",
  //   name: "Idzie mi coraz lepiej",
  //   time: "15 : 44",
  // },
  // {
  //   id: 81,
  //   cover: "../images/upcome/91.jpg",
  //   name: "Wszystko pod kontrolą",
  //   time: "11 : 10",
  // },
  // {
  //   id: 82,
  //   cover: "../images/upcome/92.jpg",
  //   name: "Gdzie jest moja beczułka z miodzikiem?",
  //   time: "12 : 58",
  // },
  // {
  //   id: 83,
  //   cover: "../images/upcome/93.jpg",
  //   name: "Widzę ją - stoi na stole",
  //   time: "12 : 58",
  // },
  // {
  //   id: 84,
  //   cover: "../images/upcome/94.jpg",
  //   name: "Teraz jestem spokojny",
  //   time: "12 : 58",
  // },
  // {
  //   id: 85,
  //   cover: "../images/upcome/95.jpg",
  //   name: "Ten mały miś strasznie się rozpycha",
  //   time: "11 : 56",
  // },
  // {
  //   id: 86,
  //   cover: "../images/upcome/96.jpg",
  //   name: "Dobra, niech mu będzie",
  //   time: "11 : 56",
  // },
  // {
  //   id: 87,
  //   cover: "../images/upcome/97.jpg",
  //   name: "Zjadłem wszystko",
  //   time: "11 : 56",
  // },
  // {
  //   id: 88,
  //   cover: "../images/upcome/98.jpg",
  //   name: "Mogę się pobawić butelką",
  //   time: "11 : 54",
  // },
  // {
  //   id: 89,
  //   cover: "../images/upcome/99.jpg",
  //   name: "Dlaczego jest taka lekka?",
  //   time: "11 : 55",
  // },
  // {
  //   id: 90,
  //   cover: "../images/upcome/101.jpg",
  //   name: "Zobaczę, czy nie zostało trochę mleczka",
  //   time: "11 : 56",
  // },
  // {
  //   id: 91,
  //   cover: "../images/upcome/102.jpg",
  //   name: "Co by tu powiedzieć mądrego?",
  //   time: "12 : 38",
  // },
  // {
  //   id: 92,
  //   cover: "../images/upcome/103.jpg",
  //   name: "Ale Was nabrałem!",
  //   time: "12 : 38",
  // },
  // {
  //   id: 93,
  //   cover: "../images/upcome/104.jpg",
  //   name: "Pomagam mamie w kuchni",
  //   time: "15 : 40",
  // },
  // {
  //   id: 94,
  //   cover: "../images/upcome/105.jpg",
  //   name: "W sypialni rodziców",
  //   time: "19 : 39",
  // },
  // {
  //   id: 95,
  //   cover: "../images/upcome/106.jpg",
  //   name: "Lubię piękne wnętrza",
  //   time: "19 : 37",
  // },
  // {
  //   id: 96,
  //   cover: "../images/upcome/114.jpg",
  //   name: "Śmiech to zdrowie",
  //   time: "19 : 37",
  // },
  // {
  //   id: 97,
  //   cover: "../images/upcome/107.jpg",
  //   name: "W barokowej scenerii",
  //   time: "19 : 44",
  // },
  // {
  //   id: 98,
  //   cover: "../images/upcome/108.jpg",
  //   name: "W pościeli rodziców najwygodniej",
  //   time: "19 : 44",
  // },
  // {
  //   id: 99,
  //   cover: "../images/upcome/109.jpg",
  //   name: "Słodki sen",
  //   time: "19 : 53",
  // },
  // {
  //   id: 100,
  //   cover: "../images/upcome/110.jpg",
  //   name: "Z mamą na spacerze",
  //   time: "20 : 25",
  // },
  // {
  //   id: 101,
  //   cover: "../images/upcome/111.jpg",
  //   name: "Tata i ja",
  //   time: "20 : 27",
  // },
  // {
  //   id: 102,
  //   cover: "../images/upcome/112.jpg",
  //   name: "Usłyszałem ptaszka w lesie",
  //   time: "09 : 21",
  // },
  // {
  //   id: 103,
  //   cover: "../images/upcome/113.jpg",
  //   name: "Las jest zielony",
  //   time: "09 : 22",
  // },
  // {
  //   id: 104,
  //   cover: "../images/upcome/115.jpg",
  //   name: "Po przerwie wróciłem do smoczka",
  //   time: "15 : 19",
  // },
  // {
  //   id: 105,
  //   cover: "../images/upcome/116.jpg",
  //   name: "Z wiernym druhem misiem",
  //   time: "09 : 22",
  // },
  // {
  //   id: 106,
  //   cover: "../images/upcome/120.jpg",
  //   name: "Teraz miś śpi, a ja czuwam",
  //   time: "09 : 24",
  // },
  // {
  //   id: 107,
  //   cover: "../images/upcome/119.jpg",
  //   name: "Czas na butelkę",
  //   time: "09 : 22",
  // },
  // {
  //   id: 108,
  //   cover: "../images/upcome/117.jpg",
  //   name: "Na brzuszku można poczytać",
  //   time: "09 : 22",
  // },
  // {
  //   id: 109,
  //   cover: "../images/upcome/118.jpg",
  //   name: "... i pooglądać",
  //   time: "09 : 22",
  // },
  // {
  //   id: 110,
  //   cover: "../images/upcome/121.jpg",
  //   name: "Bawię się z tatą",
  //   time: "16 : 09",
  // },
  // {
  //   id: 111,
  //   cover: "../images/upcome/122.jpg",
  //   name: "Jutro mam święto",
  //   time: "15 : 50",
  // },
  // {
  //   id: 112,
  //   cover: "../images/upcome/123.jpg",
  //   name: "Kto mi złoży życzenia urodzinowe?",
  //   time: "15 : 50",
  // },
  // {
  //   id: 113,
  //   cover: "../images/upcome/124.jpg",
  //   name: "Wygodna, ale wolę fotelik",
  //   time: "16 : 05",
  // },
  // {
  //   id: 114,
  //   cover: "../images/upcome/125.jpg",
  //   name: "Czas na codzienną lekturę",
  //   time: "12 : 16",
  // },
  // {
  //   id: 115,
  //   cover: "../images/upcome/126.jpg",
  //   name: "Dlaczego tu nie ma liter?",
  //   time: "12 : 16",
  // },
  // {
  //   id: 116,
  //   cover: "../images/upcome/127.jpg",
  //   name: "Ma sie tych przyjaciół",
  //   time: "12 : 54",
  // },
  // {
  //   id: 117,
  //   cover: "../images/upcome/128.jpg",
  //   name: "Po raz pierwszy zasnąłem w łóżeczku",
  //   time: "09 : 28",
  // },
  // {
  //   id: 118,
  //   cover: "../images/upcome/129.jpg",
  //   name: "Po dobrze przespanej nocy",
  //   time: "10 : 03",
  // },
  // {
  //   id: 119,
  //   cover: "../images/upcome/130.jpg",
  //   name: "Świat jest piękny!",
  //   time: "10 : 03",
  // },
  // {
  //   id: 120,
  //   cover: "../images/upcome/131.jpg",
  //   name: "Szukam ząbków",
  //   time: "10 : 55",
  // },
  // {
  //   id: 121,
  //   cover: "../images/upcome/132.jpg",
  //   name: "Gdzie one są?",
  //   time: "10 : 55",
  // },
  // {
  //   id: 122,
  //   cover: "../images/upcome/133.jpg",
  //   name: "Smoczka też można gryźć",
  //   time: "11 : 37",
  // },
  // {
  //   id: 123,
  //   cover: "../images/upcome/134.jpg",
  //   name: "Przerwa na uśmiech",
  //   time: "11 : 37",
  // },
  // {
  //   id: 124,
  //   cover: "../images/upcome/135.jpg",
  //   name: "Chwila zadumy",
  //   time: "11 : 37",
  // },
  // {
  //   id: 125,
  //   cover: "../images/upcome/136.jpg",
  //   name: "Ale o co chodzi?",
  //   time: "15 : 29",
  // },
  // {
  //   id: 126,
  //   cover: "../images/upcome/137.jpg",
  //   name: "Świat jest dziwny",
  //   time: "15 : 28",
  // },
  // {
  //   id: 127,
  //   cover: "../images/upcome/138.jpg",
  //   name: "Małe przytulanko",
  //   time: "16 : 22",
  // },
  // {
  //   id: 128,
  //   cover: "../images/upcome/139.jpg",
  //   name: "Czasami gdzieś się wybieram",
  //   time: "10 : 01",
  // },
  // {
  //   id: 129,
  //   cover: "../images/upcome/140.jpg",
  //   name: "Moje wdzianko wyjściowe",
  //   time: "10 : 01",
  // },
];

export const recommended2 = [
  {
    id: 1,
    cover: "../images/1.jpg",
    name: "11.11.2022",
    time: "Marsz Święta Niepodległości w Warszawie",
    date: "",
  },
  {
    id: 2,
    cover: "../images/3.jpg",
    name: "13.09.2022",
    time: "Świeżo upieczony Licencjat",
    date: "",
  },
  {
    id: 3,
    cover: "../images/9.jpg",
    name: "2021",
    time: "Domaniów",
    date: "",
  },
  {
    id: 4,
    cover: "../images/5.jpg",
    name: "01.03.2021",
    time: "Wycieczka",
    date: "",
  },
  {
    id: 5,
    cover: "../images/4.jpg",
    name: "15.09.2021",
    time: "Sandomierz",
    date: "",
  },
  {
    id: 6,
    cover: "../images/11.jpg",
    name: "2021",
    time: "Wycieczka romantyczna",
    date: "",
  },
  {
    id: 7,
    cover: "../images/12.jpg",
    name: "2021",
    time: "Na wycieczce",
    date: "",
  },
  {
    id: 8,
    cover: "../images/13.jpg",
    name: "2021",
    time: "Na wycieczce",
    date: "",
  },
  {
    id: 9,
    cover: "../images/24.jpg",
    name: "2020",
    time: "4 urodziny",
    date: "",
  },
  {
    id: 10,
    cover: "../images/25.jpg",
    name: "2020",
    time: "13 : 03",
    date: "",
  },
  {
    id: 11,
    cover: "../images/26.jpg",
    name: "2020",
    time: "Ulubione dinozaury",
    date: "",
  },
  {
    id: 12,
    cover: "../images/16.jpg",
    name: "2019",
    time: "3 urodziny",
    date: "",
  },
  // {
  //   id: 13,
  //   cover: "../images/assets/14.jpg",
  //   name: "28.09.2022",
  //   time: "19 : 30",
  //   date: "",
  // },
  // {
  //   id: 14,
  //   cover: "../images/assets/15.jpg",
  //   name: "28.09.2022",
  //   time: "19 : 32",
  //   date: "",
  // },
  // {
  //   id: 15,
  //   cover: "../images/assets/16.jpg",
  //   name: "01.10.2022",
  //   time: "17 : 48",
  //   date: "",
  // },
  // {
  //   id: 16,
  //   cover: "../images/assets/17.jpg",
  //   name: "01.10.2022",
  //   time: "17 : 48",
  //   date: "",
  // },
  // {
  //   id: 17,
  //   cover: "../images/assets/18.jpg",
  //   name: "01.10.2022",
  //   time: "17 : 49",
  //   date: "",
  // },
  // {
  //   id: 18,
  //   cover: "../images/assets/19.jpg",
  //   name: "02.10.2022",
  //   time: "16 : 35",
  //   date: "",
  // },
  // {
  //   id: 19,
  //   cover: "../images/assets/20.jpg",
  //   name: "02.10.2022",
  //   time: "16 : 35",
  //   date: "",
  // },
  // {
  //   id: 20,
  //   cover: "../images/assets/21.jpg",
  //   name: "02.10.2022",
  //   time: "16 : 36",
  //   date: "",
  // },
  // {
  //   id: 21,
  //   cover: "../images/assets/22.jpg",
  //   name: "02.10.2022",
  //   time: "18 : 20",
  //   date: "",
  // },
  // {
  //   id: 22,
  //   cover: "../images/assets/23.jpg",
  //   name: "09.10.2022",
  //   time: "14 : 46",
  //   date: "",
  // },
  // {
  //   id: 23,
  //   cover: "../images/assets/24.jpg",
  //   name: "10.10.2022",
  //   time: "16 : 53",
  //   date: "",
  // },
  // {
  //   id: 24,
  //   cover: "../images/assets/25.jpg",
  //   name: "14.10.2022",
  //   time: "10 : 44",
  //   date: "",
  // },
  // {
  //   id: 25,
  //   cover: "../images/assets/26.jpg",
  //   name: "14.10.2022",
  //   time: "13 : 32",
  //   date: "",
  // },
  // {
  //   id: 26,
  //   cover: "../images/assets/27.jpg",
  //   name: "14.10.2022",
  //   time: "13 : 33",
  //   date: "",
  // },
  // {
  //   id: 27,
  //   cover: "../images/assets/28.jpg",
  //   name: "14.10.2022",
  //   time: "13 : 48",
  //   date: "",
  // },
  // {
  //   id: 28,
  //   cover: "../images/assets/29.jpg",
  //   name: "14.10.2022",
  //   time: "13 : 48",
  //   date: "",
  // },
  // {
  //   id: 29,
  //   cover: "../images/assets/30.jpg",
  //   name: "16.10.2022",
  //   time: "15 : 28",
  //   date: "",
  // },
  // {
  //   id: 30,
  //   cover: "../images/assets/31.jpg",
  //   name: "16.10.2022",
  //   time: "15 : 29",
  //   date: "",
  // },
  // {
  //   id: 31,
  //   cover: "../images/assets/32.jpg",
  //   name: "16.10.2022",
  //   time: "19 : 57",
  //   date: "",
  // },
  // {
  //   id: 32,
  //   cover: "../images/assets/33.jpg",
  //   name: "19.10.2022",
  //   time: "13 : 35",
  //   date: "",
  // },
  // {
  //   id: 33,
  //   cover: "../images/assets/34.jpg",
  //   name: "19.10.2022",
  //   time: "15 : 10",
  //   date: "",
  // },
  // {
  //   id: 34,
  //   cover: "../images/assets/35.jpg",
  //   name: "19.10.2022",
  //   time: "15 : 10",
  //   date: "",
  // },
  // {
  //   id: 35,
  //   cover: "../images/assets/36.jpg",
  //   name: "19.10.2022",
  //   time: "15 : 10",
  //   date: "",
  // },
  // {
  //   id: 36,
  //   cover: "../images/assets/37.jpg",
  //   name: "21.10.2022",
  //   time: "12 : 30",
  //   date: "",
  // },
  // {
  //   id: 37,
  //   cover: "../images/assets/38.jpg",
  //   name: "21.10.2022",
  //   time: "12 : 31",
  //   date: "",
  // },
  // {
  //   id: 38,
  //   cover: "../images/assets/39.jpg",
  //   name: "21.10.2022",
  //   time: "17 : 35",
  //   date: "",
  // },
  // {
  //   id: 39,
  //   cover: "../images/assets/40.jpg",
  //   name: "21.10.2022",
  //   time: "17 : 36",
  //   date: "",
  // },
  // {
  //   id: 40,
  //   cover: "../images/assets/41.jpg",
  //   name: "21.10.2022",
  //   time: "18 : 21",
  //   date: "",
  // },
  // {
  //   id: 41,
  //   cover: "../images/assets/42.jpg",
  //   name: "26.10.2022",
  //   time: "17 : 43",
  //   date: "",
  // },
];
